in_domains: cfp
data_path: 'data' # Change me
csv_path: 'data'
label_column: ''
nb_classes: 3
having_test_set: True
traintest: False

# Finetune from:
finetune: 'path'
resume: ''
output_dir: 'output/finetune'

# Train
epochs: 50
batch_size: 16
blr: 5e-4
layer_decay: 0.65
drop_path: 0.2
min_lr: 1e-6
warmup_epochs: 10
input_size: 224
weight_decay: 0.05

use_mean_pooling: True
init_scale: 0.001

# Wandb logging
log_wandb: False
log_tensorboard: False
wandb_project: 'finetune'
wandb_entity: null # Change if needed
wandb_run_name: wandb

save_confusion_matrix: True

# Architecture
model: multivit_large
patch_size: 16
num_global_tokens: 1
